package com.skysoft.vaultlogic.common.mapper;

class DataMapperException extends RuntimeException {
    DataMapperException(String message, Throwable cause) {
        super(message, cause);
    }
}
